### ISSUE TITLE
GROUP BY query can lead to nullpointer in sesame 

### ISSUE THREAD

**Issue by JervenBolleman** [openlink/virtuoso-opensource#172]
```
java.lang.NullPointerException                                                                                      
        at virtuoso.sesame2.driver.VirtuosoRepositoryConnection$CloseableIterationBase.moveForward(Unknown Source)  
        at virtuoso.sesame2.driver.VirtuosoRepositoryConnection$CloseableIterationBase.hasNext(Unknown Source)      
        at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68)                                  
        at org.expasy.sesame.web.handlers.HTMLHandler.evaluateTupleQuery(HTMLHandler.java:226)
```

Generated with the following query on the uniprot dataset.

```
SELECT ?graph (COUNT(?s) AS ?inGraph
WHERE {
VALUES (?graph) {(<http://beta.sparql.uniprot.org/uniref/>) (<http://beta.sparql.uniprot.org/uniparc/>) (<http://beta.sparql.uniprot.org/uniprot/>)}
GRAPH ?graph {?s ?p ?o}
}
```

**Comment by JervenBolleman** [comment]
I suspect that the result set [here](https://github.com/openlink/virtuoso-opensource/blob/develop/7/binsrc/sesame2/virtuoso_driver/VirtuosoRepositoryConnection.java#L2749) is null

**Comment by smalinin** [comment]
Could you try recreate issue with next version of Sesame2 provider https://dl.dropboxusercontent.com/u/108448522/virt_sesame2.jar ? It was compiled with debug info. The ResultSet could not be null in place that you mean.

**Comment by JervenBolleman** [comment]
The bug does not seem to happen with this jar, was it possible in an earlier release?

**Comment by smalinin** [comment]
Ok, thanks. The GIT sources will be updated soon.
