### ISSUE TITLE
Class cast exception at VirtuosoRepositoryConnection.executeSPARQLForHandler

### ISSUE THREAD

**Issue by JervenBolleman** [openlink/virtuoso-opensource#178]
```
 Exception:java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String                          
        at virtuoso.sesame2.driver.VirtuosoRepositoryConnection.executeSPARQLForHandler(Unknown Source)             
        at virtuoso.sesame2.driver.VirtuosoRepositoryConnection$1.evaluate(Unknown Source)                          
        at org.expasy.sesame.web.handlers.PlainTextHandler.returnPlainText(PlainTextHandler.java:87)     
```

Jars from commit bea4a6da40258afeebf4be3e18f299ec8f11967c

**Comment by JervenBolleman** [comment]
Could be related to #161

**Comment by JervenBolleman** [comment]
[castValue method](https://github.com/openlink/virtuoso-opensource/blob/develop/7/binsrc/sesame2/virtuoso_driver/VirtuosoRepositoryConnection.java#L2541) does not have a case for java.lang.Long. Still can't figure out how it was triggered.

**Comment by smalinin** [comment]
Yes, case for java.lang.Long isn't existed, but it could not throw the exception above. Could you give some example for exception? (SPARQL query and java code )

**Comment by JervenBolleman** [comment]
The query is

```
SELECT (COUNT(*) AS ?no) { ?s ?p ?o  }
```

On a dataset with more than 13 billion triples.

Code accessing it is implementing a sesame TupleQueryResultHandler. But the class cast exception is in the virtuoso layer.

**Comment by smalinin** [comment]
Did you use java code like the next ?

```
  con = repository.getConnection();
  TupleQuery query = con.prepareTupleQuery(QueryLanguage.SPARQL,
             "SELECT (COUNT(*) AS ?no) { ?s ?p ?o  }");
  TupleQueryResult queryResult = query.evaluate();
  while (queryResult.hasNext()) {
    BindingSet Rows = queryResult.next();
    System.out.println("Rows:"+Rows);
  }
  queryResult.close();          
```

**Comment by JervenBolleman** [comment]
No more like this

``` java
 con = repository.getConnection();
  TupleQuery query = con.prepareTupleQuery(QueryLanguage.SPARQL,
             "SELECT (COUNT(*) AS ?no) { ?s ?p ?o  }");
  TupleQueryResult queryResult = query.evaluate(new TupleQueryHandler(){
  @Override
        public void handleSolution(final BindingSet arg0)
            throws TupleQueryResultHandlerException
        {
            for (String bindingName:arg0.getBindingNames()){
                              System.out.print(arg0.getValue(bindingName));
                              System.out.print('\t');
                        }
                        System.out.println();
        }
  });

  queryResult.close(); 

```

**Comment by smalinin** [comment]
I could not found TupleQueryHandler class in Sesame, so may be you mean:
(the evaluate method require TupleQueryResultHandler)

```
    TupleQuery query = con.prepareTupleQuery(QueryLanguage.SPARQL,
             "SELECT (COUNT(*)+13000000000 AS ?no) { ?s ?p ?o  }");
    query.evaluate(new TupleQueryResultHandler(){
            public void handleSolution(final BindingSet arg0)
                    throws TupleQueryResultHandlerException
            {
                    for (String bindingName:arg0.getBindingNames()){
                              System.out.print(arg0.getValue(bindingName));
                              System.out.print('\t');
                        }
                        System.out.println();
            }
            public void endQueryResult(){}
            public void startQueryResult(List<String> bindingNames){}
            public void handleLinks(List<String> linkUrls) {}
            public void handleBoolean(boolean value) {}
    });
```

Output is:

```
  "13000037276"
```

**Comment by JervenBolleman** [comment]
Yes, but sometimes I get a class cast... Can you try it with the virt_sesame2.jar on github to see if its different from your development version?

**Comment by smalinin** [comment]
Sorry for delay. You are right, the problem is because virt_sesame2.jar file was not updated with a fresh binary, after the source fixing. I write about this issue to repository administrator. 
Now you could rebuild jar from sources, it will fix the issue.

**Comment by JervenBolleman** [comment]
Had does one rebuild the jars? make all does not seem to do so!
