### ISSUE TITLE
Crash on bulk upload using Virtuoso Jena provider

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#250]
Hi, I am trying to use Virtuoso's Jena Provider to bulk upload a Jena Model that contains about 10 million triples.  It runs smoothy for the first 900,000 or so triples and then crashes with the below error.  My copy of the Virtuoso Jena provider is the latest.  - Erich

Exception in thread "main" com.hp.hpl.jena.shared.JenaException: org.apache.jena.atlas.lib.InternalErrorException: Invalid id node for object (null node): ([0000000002F12F18], [0000000000016041], [000000001ED1F9B9])
    at virtuoso.jena.driver.VirtGraph.add(VirtGraph.java:768)
    at virtuoso.jena.driver.VirtBulkUpdateHandler.addIterator(VirtBulkUpdateHandler.java:63)
    at com.hp.hpl.jena.graph.impl.SimpleBulkUpdateHandler.add(SimpleBulkUpdateHandler.java:89)
    at edu.stonybrook.bmi.tcga.server.main(server.java:32)
Caused by: org.apache.jena.atlas.lib.InternalErrorException: Invalid id node for object (null node): ([0000000002F12F18], [0000000000016041], [000000001ED1F9B9])
    at com.hp.hpl.jena.tdb.lib.TupleLib.triple(TupleLib.java:139)
    at com.hp.hpl.jena.tdb.lib.TupleLib.triple(TupleLib.java:114)
    at com.hp.hpl.jena.tdb.lib.TupleLib.access$000(TupleLib.java:45)
    at com.hp.hpl.jena.tdb.lib.TupleLib$3.convert(TupleLib.java:76)
    at com.hp.hpl.jena.tdb.lib.TupleLib$3.convert(TupleLib.java:72)
    at org.apache.jena.atlas.iterator.Iter$4.next(Iter.java:323)
    at org.apache.jena.atlas.iterator.Iter$4.next(Iter.java:323)
    at org.apache.jena.atlas.iterator.Iter$4.next(Iter.java:323)
    at org.apache.jena.atlas.iterator.Iter.next(Iter.java:921)
    at com.hp.hpl.jena.util.iterator.WrappedIterator.next(WrappedIterator.java:94)
    at virtuoso.jena.driver.VirtGraph.add(VirtGraph.java:737)
    ... 3 more

**Comment by ebremer** [comment]
tracked it back to Apache Jena.  The data loaded fine.  It's not Virtuoso.
