### ISSUE TITLE
Throw exception when reading polygon geometry by JDBC 

### ISSUE THREAD

**Issue by wushengcq** [openlink/virtuoso-opensource#407]
Hi ~
I have stored some RDF file with spatial data into virtuoso, and want to query it by using Virtuoso JDBC driver. I'm fine withe the point data. When searching the polygon data, JDBC driver throw a exception : 

virtuoso.jdbc4.VirtuosoException: General error
    at virtuoso.jdbc4.VirtuosoInputStream.readRdfBox(VirtuosoInputStream.java:472)
    at virtuoso.jdbc4.VirtuosoInputStream.read_object(VirtuosoInputStream.java:259)
    at virtuoso.jdbc4.VirtuosoInputStream.read_object(VirtuosoInputStream.java:70)
    at virtuoso.jdbc4.VirtuosoInputStream.read_object(VirtuosoInputStream.java:70)
    at virtuoso.jdbc4.VirtuosoInputStream.read_object(VirtuosoInputStream.java:70)
    at virtuoso.jdbc4.VirtuosoConnection.read_request(VirtuosoConnection.java:486)
    at virtuoso.jdbc4.VirtuosoFuture.nextResult(VirtuosoFuture.java:55)
    at virtuoso.jdbc4.VirtuosoResultSet.process_result(VirtuosoResultSet.java:215)
    at virtuoso.jdbc4.VirtuosoResultSet.<init>(VirtuosoResultSet.java:58)
    at virtuoso.jdbc4.VirtuosoStatement.sendQuery(VirtuosoStatement.java:138)
    at virtuoso.jdbc4.VirtuosoStatement.executeQuery(VirtuosoStatement.java:230)
Caused by: java.lang.NumberFormatException: For input string: "N((-110.329540"
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
    at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
    at java.lang.Double.parseDouble(Double.java:538)
    at virtuoso.jdbc4.VirtuosoPoint.<init>(VirtuosoPoint.java:21)
    at virtuoso.jdbc4.VirtuosoInputStream.readRdfBox(VirtuosoInputStream.java:470)
    ... 36 more

It seem as there is something wrong with substring to polygon WKT string. 
I also executed the same sparql in virtuoso conductor, and got the right results :

 POLYGON((-110.329540 31.341061,-110.333502 31.354768,-110.326294 31.368595,-110.290215 31.415757,-110.288045 31.414387,-110.228000 31.341061,-110.329540 31.341061))

**Comment by HughWilliams** [comment]
What is the version of the Virtuoso JDBC Driver (java -jar virtjdbc4.jar) and Virtuoso server (virtuoso-t -?) being used ?

**Comment by wushengcq** [comment]
Hello !
This is the version which I'm using:
JDBC virtjebc4.jar:

> OpenLink Virtuoso(TM) Driver for JDBC(TM) Version 4.x [Build 3.76]

Virtuoso server: 

> Virtuoso Open Source Edition (Column Store) (multi threaded)
> Version 7.2.0.3212-pthreads as of Feb 27 2015
> Compiled for Linux (x86_64-unknown-linux-gnu)

I just print the geometry type by  bif:GeometryType() function in Virtuoso Conductor, and the results are all "POLYGON".  

Thanks ~

**Comment by wushengcq** [comment]
There is another strange thing with the JDBC Driver.

**When I load the virtuoso jdbc3 driver**

``` java
Class.forName("virtuoso.jdbc3.Driver");
```

the exception throw by jdbc4 package:

> virtuoso.jdbc4.VirtuosoException: General error
> at virtuoso.jdbc4.VirtuosoInputStream.readRdfBox(VirtuosoInputStream.java:472)
> at virtuoso.jdbc4.VirtuosoInputStream.read_object(VirtuosoInputStream.java:259)
> at virtuoso.jdbc4.VirtuosoInputStream.read_object(VirtuosoInputStream.java:70)
> at virtuoso.jdbc4.VirtuosoInputStream.read_object(VirtuosoInputStream.java:70)
> at virtuoso.jdbc4.VirtuosoInputStream.read_object(VirtuosoInputStream.java:70)

**But, when I load the virtuoso jdbc4 driver**

``` java
Class.forName("virtuoso.jdbc4.Driver");
```

the exception throw by jdbc4 package:

> virtuoso.jdbc3.VirtuosoException: General error
> at virtuoso.jdbc3.VirtuosoInputStream.readRdfBox(VirtuosoInputStream.java:472)
> at virtuoso.jdbc3.VirtuosoInputStream.read_object(VirtuosoInputStream.java:259)
> at virtuoso.jdbc3.VirtuosoInputStream.read_object(VirtuosoInputStream.java:70)
> at virtuoso.jdbc3.VirtuosoInputStream.read_object(VirtuosoInputStream.java:70)
> at virtuoso.jdbc3.VirtuosoInputStream.read_object(VirtuosoInputStream.java:70)

**Comment by openlink** [comment]
A patch for the POLYGON exception has been pushed in the latest develop/7 branch.

**Comment by wushengcq** [comment]
Thanks you very much !!
I will try the latest version immediately.

On Fri, May 22, 2015 at 2:30 PM, OpenLink Software <notifications@github.com
