### ISSUE TITLE
ADO.NET provider: Int32 overflow in VirtuosoDataReader.GetValues

### ISSUE THREAD

**Issue by drassokhin** [openlink/virtuoso-opensource#445]
VirtuosoDataReader.GetValues(object[] rowData) throws OverflowException on an attempt to retrieve an integer value that exceeds the range of the Int32 type:

Value was either too large or too small for an Int32.
Stack trace:
  at System.Convert.ToInt32(Int64 value)
   at System.Int64.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at OpenLink.Data.Virtuoso.VirtuosoDataReader.GetColumnData(Int32 i)
   at OpenLink.Data.Virtuoso.VirtuosoDataReader.GetValues(Object[] values)
   at ...

I encountered this exception when executing the triple counting query against a triple store with a very large number of triples:
select (count(?p) as ?Count)
where
{
  [] ?p []
}

**Comment by smalinin** [comment]
Fixed
