### ISSUE TITLE
Can't use SPARQL over JDBC in DataGrip

### ISSUE THREAD

**Issue by yonyonson** [openlink/virtuoso-opensource#537]
Hei,

I am running Virt 7.2.2 Open source edition on Ubuntu 14.04 and trying to access is with jetBrains DataGrip 1.0.3 on Mac OS X El Capitan. I am setting up driver and connecton as described here: http://wikis.openlinksw.com/dataspace/owiki/wiki/UdaWikiWeb/JDBCJetBrainsDataGrip (using `virtjdbc4.jar` ).
There is almost no data in Virtuoso (200-300 triples).
However, I am getting exception when trying to send SPARQL over JDBC. Here is query that is being sent and exception:
Query:

```
sparql
select distinct ?g where {graph ?g {?s ?p ?o}} order by ?g
;
```

Exception:

```
[2016-02-25 13:47:21] [42000][-3] java.lang.ClassCastException:java.lang.Short cannot be cast to openlink.util.Vector
java.lang.Error: java.lang.ClassCastException:java.lang.Short cannot be cast to openlink.util.Vector
    at virtuoso.jdbc4.VirtuosoConnection.read_request(VirtuosoConnection.java:974)
    at virtuoso.jdbc4.VirtuosoFuture.nextResult(VirtuosoFuture.java:151)
    at virtuoso.jdbc4.VirtuosoResultSet.process_result(VirtuosoResultSet.java:446)
    at virtuoso.jdbc4.VirtuosoResultSet.<init>(VirtuosoResultSet.java:206)
    at virtuoso.jdbc4.VirtuosoStatement.sendQuery(VirtuosoStatement.java:260)
    at virtuoso.jdbc4.VirtuosoStatement.execute(VirtuosoStatement.java:412)
    at com.intellij.database.remote.jdbc.impl.RemoteStatementImpl.execute(RemoteStatementImpl.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
    at sun.rmi.transport.Transport$1.run(Transport.java:200)
    at sun.rmi.transport.Transport$1.run(Transport.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$256(TCPTransport.java:683)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[2016-02-25 13:47:21] java.lang.ArrayIndexOutOfBoundsException: 16
    at virtuoso.jdbc4.VirtuosoInputStream.convByte2UTF(VirtuosoInputStream.java:539)
    at virtuoso.jdbc4.VirtuosoInputStream.read_object(VirtuosoInputStream.java:312)
    at virtuoso.jdbc4.VirtuosoInputStream.read_object(VirtuosoInputStream.java:180)
    at virtuoso.jdbc4.VirtuosoInputStream.read_object(VirtuosoInputStream.java:180)
    at virtuoso.jdbc4.VirtuosoInputStream.read_object(VirtuosoInputStream.java:180)
    at virtuoso.jdbc4.VirtuosoConnection.read_request(VirtuosoConnection.java:915)
    at virtuoso.jdbc4.VirtuosoFuture.nextResult(VirtuosoFuture.java:151)
    at virtuoso.jdbc4.VirtuosoStatement.close_rs(VirtuosoStatement.java:354)
    at virtuoso.jdbc4.VirtuosoStatement.close(VirtuosoStatement.java:390)
    at com.intellij.database.remote.jdbc.impl.RemoteStatementImpl.close(RemoteStatementImpl.java:29)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
    at sun.rmi.transport.Transport$1.run(Transport.java:200)
    at sun.rmi.transport.Transport$1.run(Transport.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$256(TCPTransport.java:683)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:276)
    at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:253)
    at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162)
    at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:217)
    at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:171)
    at com.sun.proxy.$Proxy113.close(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.execution.rmi.RemoteUtil.invokeRemote(RemoteUtil.java:124)
    at com.intellij.execution.rmi.RemoteUtil.access$100(RemoteUtil.java:36)
    at com.intellij.execution.rmi.RemoteUtil$RemoteInvocationHandler.invoke(RemoteUtil.java:229)
    at com.sun.proxy.$Proxy114.close(Unknown Source)
    at com.intellij.database.console.JdbcEngine.a(JdbcEngine.java:1106)
    at com.intellij.database.console.JdbcEngine.a(JdbcEngine.java:429)
    at com.intellij.database.console.JdbcEngine.access$400(JdbcEngine.java:57)
    at com.intellij.database.console.JdbcEngine$4.compute(JdbcEngine.java:233)
    at com.intellij.database.console.JdbcEngine$4.compute(JdbcEngine.java:230)
    at com.intellij.database.console.AbstractEngine$5.compute(AbstractEngine.java:201)
    at com.intellij.database.console.AbstractEngine$5.compute(AbstractEngine.java:195)
    at com.intellij.database.console.AbstractEngine$4.run(AbstractEngine.java:180)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by HughWilliams** [comment]
@yonyonson: I am able to configure JetBrain DataGrip 1.0.3 to query my Virtuoso 7.2.2 instance on Mac OS X and can run the query  you provide successfully.

Note I am running Java 8 on my Mac so I user the http://opldownload.s3.amazonaws.com/uda/virtuoso/7.2/jdbc/virtjdbc4_1.jar  driver ...

Can you run a simple query to count all triple i.e. "sparql select count(*) where {?s ?p ?o}" ?

**Comment by yonyonson** [comment]
@HughWilliams Hmm, I got it to work as well. It wasn't quite cleat what should be put in Parameters dialogue of DataGrip, but I got it to work.
Thank you for assistance!
