### ISSUE TITLE
V7 Crash when executing graph load via JDBC prepared statement

### ISSUE THREAD

**Issue by miahi** [openlink/virtuoso-opensource#558]
When calling DB.DBA.RDF_LOAD_RDFXML as prepared statement through the JDBC driver _for some graphs_, Virtuoso 7 (v7.2.0 and V7.2.4 tested) crashes with "GPF: Dkpool.c:1839 large free not on 4k boundary". The JDBC driver version doesn't seem to matter (3, 4, 4_1, 4_2 tested). The same load works without prepared statement. Some of the RDF graphs I tried are not impacted by this (loading http://bd.eionet.europa.eu/article17/skos.rdf works).

Test preparation:

```
wget http://bwd.eea.europa.eu/bwd.rdf.gz
gunzip bwd.rdf.gz
```

Test program (point the _file_ var to the correct path)

```
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;

public class TestLoad {

    static String file = "/var/tmp/bwd.rdf";
    static String graph = "http://bwd.eea.europa.eu/bwd.rdf.gz";

    public static void main(String[] args) throws Exception{

        String sql = "DB.DBA.RDF_LOAD_RDFXML(file_open(?), ?, ?)";
        String sql1 = "DB.DBA.RDF_LOAD_RDFXML(file_open('" + file + "'), '" + graph + "', '" + graph + "')";

        Class.forName("virtuoso.jdbc4.Driver");
        Connection conn = DriverManager.getConnection("jdbc:virtuoso://localhost:1112/charset=UTF-8", "dba", "dba");

        System.out.println("Connected");
        System.out.println("Executing without prepared statement");

        Statement s = conn.createStatement();
        s.execute(sql1);
        s.close();

        System.out.println("Finished executing without prepared statement");
        System.out.println("Executing with prepared statement");

        PreparedStatement pstmt = null;
        try {
            pstmt = conn.prepareStatement(sql);
            System.out.println("Prepared statement compiled");
            pstmt.setString(1, file);
            pstmt.setString(2, graph);
            pstmt.setString(3, graph);
            pstmt.execute();
            System.out.println("Finished executing with prepared statement");
        } finally {
            if(pstmt != null) pstmt.close();
            conn.close();
        }
    }
}
```

Test run result:

```
java -cp .;E:\eea_cr\virtjdbc4_2.jar TestLoad
Connected
Executing without prepared statement
Finished executing without prepared statement
Executing with prepared statement
Exception in thread "main" virtuoso.jdbc4.VirtuosoException: Virtuoso Communications Link Failure (timeout) : Connection to the server lost
        at virtuoso.jdbc4.VirtuosoFuture.nextResult(VirtuosoFuture.java:63)
        at virtuoso.jdbc4.VirtuosoPreparedStatement.close(VirtuosoPreparedStatement.java:198)
        at TestLoad.main(TestLoad.java:44)
```

virtuoso.log result :

```
14:50:48 /var/local/deploy/virtuoso7/bin/virtuoso-t() [0x8ba51a]
14:50:48 /var/local/deploy/virtuoso7/bin/virtuoso-t() [0x8ba578]
14:50:48 /var/local/deploy/virtuoso7/bin/virtuoso-t() [0x8ba190]
14:50:48 /var/local/deploy/virtuoso7/bin/virtuoso-t() [0x8a9325]
14:50:48 /var/local/deploy/virtuoso7/bin/virtuoso-t() [0x61ffa2]
14:50:48 /var/local/deploy/virtuoso7/bin/virtuoso-t() [0x62127b]
14:50:48 /var/local/deploy/virtuoso7/bin/virtuoso-t() [0x5916e5]
14:50:48 /var/local/deploy/virtuoso7/bin/virtuoso-t() [0x596a00]
14:50:48 /var/local/deploy/virtuoso7/bin/virtuoso-t() [0x5bee70]
14:50:48 /var/local/deploy/virtuoso7/bin/virtuoso-t() [0x5c9466]
14:50:48 /var/local/deploy/virtuoso7/bin/virtuoso-t() [0x5d1c12]
14:50:48 /var/local/deploy/virtuoso7/bin/virtuoso-t(sf_sql_execute_w+0x74) [0x5d2254]
14:50:48 /var/local/deploy/virtuoso7/bin/virtuoso-t() [0x8beab7]
14:50:48 /var/local/deploy/virtuoso7/bin/virtuoso-t() [0x8c4e7c]
14:50:48 /lib64/libpthread.so.0(+0x7dc5) [0x7fe937699dc5]
14:50:48 /lib64/libc.so.6(clone+0x6d) [0x7fe936ec128d]
14:50:48 GPF: Dkpool.c:1839 large free not on 4k boundary
```

**Comment by HughWilliams** [comment]
@miahi: I downloaded you dataset , compiled your program to run locally against my Virtuoso 7.2.4 instance and it does indeed crash but with a different error on Mac OS X anyway:

```
Hughs-MBP-2:JDBCDriverType4 hwilliams$ javac -cp .:./virtjdbc4_2.jar TestLoad.java 
Hughs-MBP-2:JDBCDriverType4 hwilliams$ java -cp .:./virtjdbc4_2.jar TestLoad
Connected
Executing without prepared statement
Finished executing without prepared statement
Executing with prepared statement
Prepared statement compiled
Exception in thread "main" virtuoso.jdbc4.VirtuosoException: Problem during closing : Broken pipe
    at virtuoso.jdbc4.VirtuosoPreparedStatement.close(VirtuosoPreparedStatement.java:205)
    at TestLoad.main(TestLoad.java:39)
Hughs-MBP-2:JDBCDriverType4 hwilliams$ 
```

virtuoso.log:

```
16:06:03 Server online at 1111 (pid 1848)
16:06:34 0   virtuoso-t                          0x0000000104f6bcba print_trace + 42
16:06:34 1   virtuoso-t                          0x0000000104f6bd88 gpf_notice + 24
16:06:34 2   virtuoso-t                          0x0000000104f4b67e dk_alloc_box + 62
16:06:34 3   virtuoso-t                          0x0000000104f5fb0e strses_string + 46
16:06:34 4   virtuoso-t                          0x0000000104960dec box_to_any_long + 220
16:06:34 5   virtuoso-t                          0x0000000104961ac9 box_to_any_1 + 3241
16:06:34 6   virtuoso-t                          0x0000000104bd0288 dc_append_box + 1304
16:06:34 7   virtuoso-t                          0x0000000104bd7811 qst_vec_set + 1009
16:06:34 8   virtuoso-t                          0x0000000104b31569 qst_set + 57
16:06:34 9   virtuoso-t                          0x0000000104adb73b ins_call_bif + 315
16:06:34 10  virtuoso-t                          0x0000000104ae2efd code_vec_run_v + 8877
16:06:34 11  virtuoso-t                          0x0000000104b33e2a qn_input + 970
16:06:34 12  virtuoso-t                          0x0000000104b40da7 qr_exec + 3047
16:06:34 13  virtuoso-t                          0x0000000104b4c5d4 sf_sql_execute + 5220
16:06:34 14  virtuoso-t                          0x0000000104b4ce5a sf_sql_execute_w + 394
16:06:34 15  virtuoso-t                          0x0000000104f75e78 future_wrapper + 696
16:06:34 16  virtuoso-t                          0x0000000104f7c15d _thread_boot + 157
16:06:34 17  libsystem_pthread.dylib             0x00007fff8d5f099d _pthread_body + 131
16:06:34 18  libsystem_pthread.dylib             0x00007fff8d5f091a _pthread_body + 0
16:06:34 19  libsystem_pthread.dylib             0x00007fff8d5ee351 thread_start + 13
16:06:34 GPF: Dkbox.c:203 box to allocate is too large
16:06:34 Server received signal 11. Continuing with the default action for that signal.
```

Thus we shall look into this ...

**Comment by miahi** [comment]
As the original file got removed (the service exposing it was stopped), I added a backup of it here: [bwd.rdf.gz](https://github.com/openlink/virtuoso-opensource/files/300392/bwd.rdf.gz)
