### ISSUE TITLE
Virtuoso Sesame 4 needs update to import org.eclipse.rdf4j packages

### ISSUE THREAD

**Issue by sdmonroe** [openlink/virtuoso-opensource#585]
The package imports in the virt-sesame-4 project need to be updated to swap org.eclipse.rdf4j for org.openrdf to comply with the latest 2.0.1 rdf4j release. I was able to change the imports on all except the VirtuosoRepositoryConfig class, see [virtuoso.zip](https://github.com/openlink/virtuoso-opensource/files/491454/virtuoso.zip). I couldn't get automake to run and swap the placeholders. Cheers.

**Comment by sdmonroe** [comment]
Hi, is there an ETA on this task? I can provide the updated sources with help on getting automake to run correctly.

**Comment by smalinin** [comment]
The updated sources are in another place https://github.com/openlink/virtuoso-opensource/tree/develop/7/binsrc/rdf4j already.

**Comment by sdmonroe** [comment]
Hi,

Thanks! When I run the test program, I get the following error. Do I need to update virtjdbc4.jar also? I'm running Virtuoso Universal Server 7.2.

```
Connection to jdbc:virtuoso://myrudi.io:80/log_enable=0 is FAILED.
ERROR Test Failed.
org.eclipse.rdf4j.repository.RepositoryException: virtuoso.jdbc4.VirtuosoException: Tag 60 not defined.
    at virtuoso.rdf4j.driver.VirtuosoRepository.getConnection(VirtuosoRepository.java:297)
    at ai.vacuity.rudi.adaptors.test.VirtuosoTest.main(VirtuosoTest.java:114)
Caused by: virtuoso.jdbc4.VirtuosoException: Tag 60 not defined.
    at virtuoso.jdbc4.VirtuosoInputStream.read_object(VirtuosoInputStream.java:263)
    at virtuoso.jdbc4.VirtuosoConnection.read_request(VirtuosoConnection.java:482)
    at virtuoso.jdbc4.VirtuosoFuture.nextResult(VirtuosoFuture.java:55)
    at virtuoso.jdbc4.VirtuosoConnection.connect(VirtuosoConnection.java:277)
    at virtuoso.jdbc4.VirtuosoConnection.connect(VirtuosoConnection.java:226)
    at virtuoso.jdbc4.VirtuosoConnection.<init>(VirtuosoConnection.java:171)
    at virtuoso.jdbc4.Driver.connect(Driver.java:58)
    at java.sql.DriverManager.getConnection(DriverManager.java:664)
    at java.sql.DriverManager.getConnection(DriverManager.java:247)
    at virtuoso.rdf4j.driver.VirtuosoRepository.getConnection(VirtuosoRepository.java:292)
    ... 1 more
```

**Comment by sdmonroe** [comment]
When I swap the URL for the amazon ec3 dn, it hangs for a few minutes, then I get this error. Same happened when I used myopenlink.net:

```
Connection to jdbc:virtuoso://[my-instance].us-west-2.compute.amazonaws.com:80/log_enable=0 is FAILED.
ERROR Test Failed.
org.eclipse.rdf4j.repository.RepositoryException: virtuoso.jdbc4.VirtuosoException: Virtuoso Communications Link Failure (timeout) : Connection to the server lost
    at virtuoso.rdf4j.driver.VirtuosoRepository.getConnection(VirtuosoRepository.java:297)
    at ai.vacuity.rudi.adaptors.test.VirtuosoTest.main(VirtuosoTest.java:114)
Caused by: virtuoso.jdbc4.VirtuosoException: Virtuoso Communications Link Failure (timeout) : Connection to the server lost
    at virtuoso.jdbc4.VirtuosoFuture.nextResult(VirtuosoFuture.java:63)
    at virtuoso.jdbc4.VirtuosoConnection.connect(VirtuosoConnection.java:277)
    at virtuoso.jdbc4.VirtuosoConnection.connect(VirtuosoConnection.java:226)
    at virtuoso.jdbc4.VirtuosoConnection.<init>(VirtuosoConnection.java:171)
    at virtuoso.jdbc4.Driver.connect(Driver.java:58)
    at java.sql.DriverManager.getConnection(DriverManager.java:664)
    at java.sql.DriverManager.getConnection(DriverManager.java:247)
    at virtuoso.rdf4j.driver.VirtuosoRepository.getConnection(VirtuosoRepository.java:292)
    ... 1 more
```

**Comment by smalinin** [comment]
Why did you use port 80 ? Are you sure, that your Virtuoso server was configured for use this port ?
Please check your file virtuoso.ini on server side, section 
...
[Parameters]
ServerPort   = 1111
...
The default Virtuoso port for remote JDBC/ODBC connections is 1111

**Comment by sdmonroe** [comment]
My virtuoso.ini does port Parameters > ServerPort to 1111. Changing the client to use 1111 works now, and all tests passed. Thanks again!!
