### ISSUE TITLE
Sql Workbench/J csv file import in Virtuoso fails on empty numeric fields

### ISSUE THREAD

**Issue by mazzogp** [openlink/virtuoso-opensource#647]
Using Sql Workbench/J and the Virtuoso JDBC driver I want to load a csv file into a Virtuoso table. I get a `NullPointerException` when in the file a numeric field is empty. 
The target table has a nullable column for the empty fields. The error is the following.

    java.lang.NullPointerException
    java.lang.NullPointerException
            at virtuoso.jdbc4.VirtuosoPreparedStatement.setObject(VirtuosoPreparedStatement.java:846)
            at virtuoso.jdbc4.VirtuosoPreparedStatement.setObject(VirtuosoPreparedStatement.java:789)
            at virtuoso.jdbc4.VirtuosoPreparedStatement.setObject(VirtuosoPreparedStatement.java:773)
            at workbench.db.compare.BatchedStatement.setObject(BatchedStatement.java:120)
            at workbench.db.importer.DataImporter.processRowData(DataImporter.java:1368)
            at workbench.db.importer.DataImporter.insertRow(DataImporter.java:1297)
            at workbench.db.importer.DataImporter.processRow(DataImporter.java:1054)
            at workbench.db.importer.TextFileParser.processOneFile(TextFileParser.java:743)
            at workbench.db.importer.AbstractImportFileParser.start(AbstractImportFileParser.java:390)
            at workbench.db.importer.DataImporter.startImport(DataImporter.java:761)
            at workbench.sql.wbcommands.WbImport.execute(WbImport.java:827)
            at workbench.sql.StatementRunner.runStatement(StatementRunner.java:582)
            at workbench.sql.BatchRunner.executeScript(BatchRunner.java:877)
            at workbench.sql.BatchRunner.executeScript(BatchRunner.java:784)
            at workbench.sql.BatchRunner.runFiles(BatchRunner.java:642)
            at workbench.sql.BatchRunner.execute(BatchRunner.java:596)
            at workbench.WbManager.runBatch(WbManager.java:1075)
            at workbench.WbManager.startApplication(WbManager.java:929)
            at workbench.WbManager.main(WbManager.java:1227)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            at java.lang.reflect.Method.invoke(Unknown Source)
            at workbench.WbStarter.main(WbStarter.java:143)
    Importing file 'C:\dev\csvFiles\CLASSIFICATION_CODE.csv' into table CLASSIFICATION_CODE
    The file "C:\dev\csvFiles\CLASSIFICATION_CODE.csv" was not imported

My table has the following structure.

    CREATE TABLE CLASSIFICATION_CODE 
    (
      CLASSIFICATION_CODE_ID NUMERIC NOT NULL ,
      CLASSIFICATION_CATEGORY VARCHAR(1) NOT NULL ,
      CLASSIFICATION_PRIORITY NUMERIC 
      CONSTRAINT PK_CLASS_CODE PRIMARY KEY (CLASSIFICATION_CODE_ID)   
    );

The file `CLASSIFICATION_CODE.csv`I am trying to upload has the following content (the last field is empty).

    CLASSIFICATION_CODE_ID,CLASSIFICATION_CATEGORY,CLASSIFICATION_PRIORITY
    1,^3^,
    2,^2^,
    3,^2^,
    4,^2^,
    5,^2^,
    6,^3^,

Finally this is the Sql Workbench/J`WbImport` command I use to import the file.

    WbImport -type=text
    -file='C:\dev\csvFiles\CLASSIFICATION_CODE.csv'
    -delimiter=,
    -table=DB.PEST.CLASSIFICATION_CODE
    -quoteChar=^
    -encoding=UTF-8
    -badfile='C:\dev\csvFiles\rejected'
    -continueOnError=true
    -multiLine=true
    -emptyStringIsNull=false;

I do not see any parameter to tell to Sql Workbench/J that the field for the column `CLASSIFICATION_PRIORITY`can be null. Unless I am missing something it might be a Virtuoso JDBC driver issue, unfortunately blocking for me.

I am using 

- Virtuoso Open Source Edition Version 7.2.4.3217-threads as of Apr 25 2016 Compiled for Win64 (x86_64-generic-win-64)
- the patched Virtuoso JDBC driver `virtjdbc4_2.jar` for  jdk1.8 located to [this link](http://id.myopenlink.net/DAV/home/smalinin/Public/JDBC/).

**Comment by smalinin** [comment]
Fixed, reload the new JDBC from link above or wait when patch will be in Git.

**Comment by smalinin** [comment]
Fixed, the fix will be in Github soon.

**Comment by mazzogp** [comment]
I have checked with my application as well. Now it works.
Thanks a million!
