### ISSUE TITLE
Jena 'statement is closed' exception

### ISSUE THREAD

**Issue by alb3rtino** [openlink/virtuoso-opensource#686]
when using the latest Jena Provider i am getting a `virtuoso.jdbc4.VirtuosoException: The statement is closed.` exception while executing the following code:

```
Dataset ds = new VirtDataset("localhost:1111", "dba", "dba");
Model m = ds.getNamedModel("urn:test:graph1");
Model m2 = ds.getNamedModel("urn:test:graph2");
m.createResource("urn:test:ResA").addProperty(RDFS.label, "Resource A");
m2.add(m);
```

throws an exception on calling `m2.add(m)`:
```
org.apache.jena.shared.JenaException: virtuoso.jdbc4.VirtuosoException: The statement is closed.
	at virtuoso.jena.driver.VirtGraph.stopBatchAdd(VirtGraph.java:1198)
	at virtuoso.jena.driver.VirtGraph.add(VirtGraph.java:1351)
	at virtuoso.jena.driver.VirtModel.add(VirtModel.java:359)
	at virtuoso.jena.driver.VirtModel.add(VirtModel.java:354)
	at virtuoso.jena.driver.VirtModel.add(VirtModel.java:365)
	at Test9_AddStatementsToModel.test(Test9_AddStatementsToModel.java:35)
```

this also happens for the methods `Model.add(List<Statement> statements)` and `Model.add(StmtIterator iter)`, but it works fine for `Model.add(Statement s)`

setup:
```
Virtuoso Open Source Edition Version 7.2.4.2.3217-pthreads
Apache Jena 3.4.0
OpenLink Virtuoso(TM) Provider for Jena(TM) Version 3.0.0 [Build 1.28]
OpenLink Virtuoso(TM) Driver for JDBC(TM) Version 4.2 [Build 3.104]
```

its working with
```
OpenLink Virtuoso(TM) Provider for Jena(TM) Version 3.0.0 [Build 1.27]
OpenLink Virtuoso(TM) Driver for JDBC(TM) Version 4.2 [Build 3.103]
```

**Comment by smalinin** [comment]
Fixed, the patch was committed.
