### ISSUE TITLE
Query ran over JDBC fails, but when run on conductor runs well

### ISSUE THREAD

**Issue by silvae86** [openlink/virtuoso-opensource#691]
Hello everyone,

I am trying to run the following query:

````
WITH GRAPH <http://127.0.0.1:3002/dendro_graph> 
DELETE 
{ 
   </r/folder/3d48499d-d7c4-4d32-9645-18fc91226b46> nie:hasLogicalPart </r/file/4bc0ef0a-cd47-4562-8d07-71d184d1f20f>. 
   </r/file/4bc0ef0a-cd47-4562-8d07-71d184d1f20f> nie:isLogicalPartOf </r/folder/3d48499d-d7c4-4d32-9645-18fc91226b46> 
} 
INSERT 
{ 
   </r/folder/fd97d6d5-3733-4bae-bc01-c653212a341c> nie:hasLogicalPart </r/file/4bc0ef0a-cd47-4562-8d07-71d184d1f20f>. 
   </r/file/4bc0ef0a-cd47-4562-8d07-71d184d1f20f> nie:isLogicalPartOf </r/folder/fd97d6d5-3733-4bae-bc01-c653212a341c> 
}; 
````

In the Conductor, it executes correctly:

![screen shot 2017-11-05 at 19 32 04](https://user-images.githubusercontent.com/2529555/32418376-6a4e9f6e-c260-11e7-9cd5-48f88bbb3a6c.png)

Via JDBC (through [node-jdbc ](https://github.com/CraZySacX/node-jdbc)wrapper) it gives me this error:

````
Error: Error running instance method
virtuoso.jdbc4.VirtuosoException: SQ074: Line 13: 
	at virtuoso.jdbc4.VirtuosoResultSet.process_result(VirtuosoResultSet.java:597)
	at virtuoso.jdbc4.VirtuosoResultSet.<init>(VirtuosoResultSet.java:174)
	at virtuoso.jdbc4.VirtuosoStatement.sendQuery(VirtuosoStatement.java:234)
	at virtuoso.jdbc4.VirtuosoStatement.executeUpdate(VirtuosoStatement.java:398)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
````

output of virtuoso-t:

````
Version 7.2.5-dev.3217-pthreads
````

Using JDBC driver `virtjdbc4_2.jar` from the folder of Virtuoso's installation

Any ideas on what it could be?

Thanks,
João

**Comment by HughWilliams** [comment]
João,

When executing the query via the JDBC (node-jdbc) which seems execute queries against a database SQL interface, are you prepending the query with the SPARQL keyword to tell Virtuoso to redirect execution of the query to the SPARQL rather then SQL engine ? i.e.

```
SPARQL
WITH GRAPH <http://127.0.0.1:3002/dendro_graph> 
DELETE 
{ 
   </r/folder/3d48499d-d7c4-4d32-9645-18fc91226b46> nie:hasLogicalPart </r/file/4bc0ef0a-cd47-4562-8d07-71d184d1f20f>. 
   </r/file/4bc0ef0a-cd47-4562-8d07-71d184d1f20f> nie:isLogicalPartOf </r/folder/3d48499d-d7c4-4d32-9645-18fc91226b46> 
} 
INSERT 
{ 
   </r/folder/fd97d6d5-3733-4bae-bc01-c653212a341c> nie:hasLogicalPart </r/file/4bc0ef0a-cd47-4562-8d07-71d184d1f20f>. 
   </r/file/4bc0ef0a-cd47-4562-8d07-71d184d1f20f> nie:isLogicalPartOf </r/folder/fd97d6d5-3733-4bae-bc01-c653212a341c> 
};
```

**Comment by silvae86** [comment]
Unfortunately yes. I prepend the SPARQL keyword followed by a \n to every SPARQL query I send to the JDBC interface. I make ASK queries, SELECT's etc... and all work. I seem to have problems with DELETEs and INSERTs though. Here is an example that works:

````
SPARQL
WITH GRAPH <http://127.0.0.1:3002/dendro_graph> 
DELETE 
{ 
 </r/file/8165bd0c-5ac1-426f-b6c1-85937d6fa42d> ?p0 ?o1 . 
 
} 
WHERE 
{ 
 </r/file/8165bd0c-5ac1-426f-b6c1-85937d6fa42d> ?p0 ?o1 . 
 
} 
INSERT DATA
{ 
 </r/file/8165bd0c-5ac1-426f-b6c1-85937d6fa42d>  <http://dendro.fe.up.pt/ontology/0.1/created>  "2017-11-05T19:24:25.844Z" .
 </r/file/8165bd0c-5ac1-426f-b6c1-85937d6fa42d>  <http://dendro.fe.up.pt/ontology/0.1/humanReadableURI>  "/r/folder/b9bfc45b-5381-429e-b660-90b84a3a0581/docxTest.docx" .
 </r/file/8165bd0c-5ac1-426f-b6c1-85937d6fa42d>  <http://dendro.fe.up.pt/ontology/0.1/fileExtension>  "docx" .
 </r/file/8165bd0c-5ac1-426f-b6c1-85937d6fa42d>  <http://dendro.fe.up.pt/ontology/0.1/hasFontAwesomeClass>  "fa-file-word-o" .
 </r/file/8165bd0c-5ac1-426f-b6c1-85937d6fa42d>  <http://dendro.fe.up.pt/ontology/0.1/modified>  "2017-11-05T19:24:26.062Z" .
 </r/file/8165bd0c-5ac1-426f-b6c1-85937d6fa42d>  <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://dendro.fe.up.pt/ontology/0.1/Resource> .
 </r/file/8165bd0c-5ac1-426f-b6c1-85937d6fa42d>  <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement> .
 </r/file/8165bd0c-5ac1-426f-b6c1-85937d6fa42d>  <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileDataObject> .
 </r/file/8165bd0c-5ac1-426f-b6c1-85937d6fa42d>  <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#title>  "docxTest.docx" .
 </r/file/8165bd0c-5ac1-426f-b6c1-85937d6fa42d>  <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#isLogicalPartOf>  </r/folder/b9bfc45b-5381-429e-b660-90b84a3a0581> .
 </r/file/8165bd0c-5ac1-426f-b6c1-85937d6fa42d>  <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#plainTextContent>  '''This is a test of an upload for the Dendro platform in Word Document XML (DOCX ) Format. ''' .
 
} 
````

Can you help me spot any relevant differences between this query and the one that does not work?

**Comment by silvae86** [comment]
I think I fixed it. This query works:

````
SPARQL
WITH GRAPH <http://127.0.0.1:3002/dendro_graph> 
DELETE 
{ 
   </r/folder/aa578a18-ca75-4dbf-8ace-0864abc88126> nie:hasLogicalPart </r/file/a0f4b1ce-9b47-46a5-982a-5c07ea8a74f8>. 
   </r/file/a0f4b1ce-9b47-46a5-982a-5c07ea8a74f8> nie:isLogicalPartOf </r/folder/aa578a18-ca75-4dbf-8ace-0864abc88126> 
} 
INSERT 
{ 
   </r/folder/56eb042f-ab23-4c43-b5d4-4b7810f28f9a> nie:hasLogicalPart </r/file/a0f4b1ce-9b47-46a5-982a-5c07ea8a74f8>. 
   </r/file/a0f4b1ce-9b47-46a5-982a-5c07ea8a74f8> nie:isLogicalPartOf </r/folder/56eb042f-ab23-4c43-b5d4-4b7810f28f9a> 
} 
````

The differences are:

- Using INSERT instead of INSERT DATA
- **No ; (semicolon) at the end of the query (I actually think this was the problem)**

I am closing the issue.
