### ISSUE TITLE
virtuoso.jdbc3.VirtuosoException: SP029: NQuads RDF loader, line 1: Whitespace is required after dot if dot is not inside decimal number, string or IRI at .@ processed pending to here.

### ISSUE THREAD

**Issue by ifourvimal** [openlink/virtuoso-opensource#725]
While running the query I am getting this error,

```
virtuoso.jdbc3.VirtuosoException: SP029: NQuads RDF loader, line 1: Whitespace is required after dot if dot is not inside decimal number, string or IRI at .@ processed pending to here.
	at virtuoso.jdbc3.VirtuosoResultSet.process_result(Unknown Source)
	at virtuoso.jdbc3.VirtuosoResultSet.getMoreResults(Unknown Source)
	at virtuoso.jdbc3.VirtuosoPreparedStatement.sendQuery(Unknown Source)
	at virtuoso.jdbc3.VirtuosoPreparedStatement.execute(Unknown Source)
	at com.bordercloud.sparql.virtuoso.InsertTTLFiletoVirtuoso.insert_data(InsertTTLFiletoVirtuoso.java:84)
	at com.bordercloud.sparql.virtuoso.InsertTTLFiletoVirtuoso.main(InsertTTLFiletoVirtuoso.java:26)


```
In my Turtle file, it's having prefix and triples.
Can I get any help?

**Comment by TallTed** [comment]
Viewing your data is the only way to explicitly advise on fixing this.  

That said, the error message seems clear -- 
>SP029: NQuads RDF loader, line 1: Whitespace is required after dot if dot is not inside decimal number, string or IRI at .@ processed pending to here.

You appear to have an instance of the string `.@` within the first line (that is, before the first `CR`/`LF`/`CRLF`) of your Turtle file.  To resolve the immediate error, insert a line feed, or a space, or a tab, or other whitespace between the `.` and the `@`.

**Comment by ifourvimal** [comment]
Here is a sample data which I am using,

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix ex: <http://example.org/stuff/1.0/> .

<http://www.w3.org/TR/rdf-syntax-grammar>
  dc:title "RDF/XML Syntax Specification (Revised)" ;
  ex:editor [
    ex:fullname "Dave Beckett";
    ex:homePage <http://purl.org/net/dajobe/>
  ] .
```

**Comment by TallTed** [comment]
Is that an accurate and exact representation of the first 10 lines of the Turtle file you're trying to load?  It does not explain the error, if so.

I wonder if there are any control or other invisible but non-white-space characters in your data file, following the trailing dots of the `@prefix` declarations...

If your file (or a gzipped archive of it) is small, I suggest attaching it to this issue, so we can review its actual content.

**Comment by ifourvimal** [comment]
Please find a below attachment of turtle file,

[test.zip](https://github.com/openlink/virtuoso-opensource/files/1813969/test.zip)

Thanks for the help.

**Comment by timhaynesopenlink** [comment]
Hi,

Thanks for that. Obviously it is valid TTL as `rapper` can parse it fine; the unzipped file loads directly in my instance:
```
SQL> ttlp(file_to_string('./test.ttl'), 'urn:test', 'urn:test', 0);

Done. -- 8 msec.
```

I see you're using JDBC. Can you tell us more about your environment, including

- the version information of virtuoso being used - run `virtuoso-t -\?` and paste the top chunk with build date etc
- what application you're using, how it gets or generates its TTL fragments, and how they're sent to Virtuoso (e.g. is there Jena or Sesame in the mix somewhere?).

I also note your test.ttl ends with a `.` and has no CR/LF thereafter so the fact it works for me might indicate a difference of versions being the problem. Could you also try my direct method of loading the TTL as above, so we can potentially eliminate JDBC as a cause?

Thanks,

**Comment by ifourvimal** [comment]
Hi @timhaynesopenlink,

I have provided information as you asked.

- The version information of virtuoso being used,

```
Virtuoso Open Source Edition (multi threaded)
Version 6.1.6.3127-threads as of Aug  2 2012
Compiled for Win32 (i686-generic-win-32)
Copyright (C) 1998-2012 OpenLink Software
```

- I am using two dependencies,

```
<dependency>
	<groupId>com.openlink.virtuoso</groupId>
	<artifactId>virtjdbc3</artifactId>
	<version>6.1.2</version>
</dependency>
<dependency>
	<groupId>com.openlink.virtuoso</groupId>
	<artifactId>virt_jena</artifactId>
	<version>6.1.6</version>
</dependency>
```

- I am using eclipse IDE to run the code.

- Below is my code snippet which I am using,

```
package com.bordercloud.sparql.virtuoso;
import java.io.*;
import java.sql.*;


public class InsertTTLFiletoVirtuoso {

  public static void main(String[] args) 
  {
    try {
      Class.forName("virtuoso.jdbc3.Driver");

      String urlDB = "jdbc:virtuoso://192.168.99.100:1111/log_enable=1";

      Connection conn = DriverManager.getConnection(urlDB,"dba","dba");
      Statement st;

      st = conn.createStatement();

      st.execute("sparql clear graph <http://192.168.99.100:1111/test1>");
      conn.setAutoCommit(false);

      String data = load_ttl("src/main/webapp/resources/outputfile/test.ttl");
      
      if (data!=null) {
        insert_data(data, "<http://192.168.99.100:1111/test1>", conn);

        // Commit or Rollback the transaction

        // conn.commit();
        // System.out.println("Commit insert");
        conn.rollback();
        System.out.println("Rollback insert");

        String query = "sparql SELECT * from <http://192.168.99.100:1111/test1> WHERE {?s ?p ?o}";
        ResultSet rs = st.executeQuery(query);
        prnRs(rs);
        rs.close();
      }
      
      
      st.close();
      conn.close();

    } catch (Exception e) {
    	e.printStackTrace();
      //System.out.println("Ex="+e);
    }
  }


  public static String load_ttl(String fname)
  {
    try {
      BufferedReader r = new BufferedReader(new FileReader(fname));
      StringBuilder sb = new StringBuilder();

      String s;
      while((s = r.readLine())!=null)
        sb.append(s);

      return sb.toString();
    } catch (Exception e) {
    }
    return null;
  }
    
  public static void insert_data(String data, String gr_name, Connection conn)
  {
     try{
       clearBulkLoadHistory(conn);
       PreparedStatement ps = conn.prepareStatement("DB.DBA.TTLP_MT (?, ?, ?, ?, ?, ?,?)");

       ps.setString(1, data);
       ps.setString(2, "");
       ps.setString(3, gr_name);
      final int NQUAD_LEVEL = 512;
       ps.setInt(4, NQUAD_LEVEL);
       ps.setInt(5, 2);
       ps.setInt(6, 1);
       ps.setInt(7, 1);

       System.out.println("Executing insert..");
       ps.execute();
       ps.close();
     } catch (Exception e) {
    	 e.printStackTrace();
       System.out.println("Ex:"+e);
     }
  }


 public static void prnRs(ResultSet rs)
 {
   try {
     ResultSetMetaData rsmd;

   System.out.println(">>>>>>>>");
     rsmd = rs.getMetaData();
     int cnt = rsmd.getColumnCount();

       while(rs.next()) {
         Object o;

         System.out.print("Thread:"+Thread.currentThread().getId()+"  ");
         for (int i = 1; i <= cnt; i++) {
           o = rs.getObject(i);
           if (rs.wasNull())
             System.out.print("<NULL> ");
           else
             System.out.print("["+ o + "] ");
         }
         System.out.println();
       }

   } catch (Exception e) {
     System.out.println(e);
     e.printStackTrace();
   }
   System.out.println(">>>>>>>>");
 }


  public static String create_query(String fname)
  {
    try {
      BufferedReader r = new BufferedReader(new FileReader(fname));
      StringBuilder sb = new StringBuilder();

      String s;
      while((s = r.readLine())!=null)
        sb.append(s);

      if (sb.length()>0)
        return "sparql insert into graph <testyear> { "+ sb.toString() + " } ";
    } catch (Exception e) {
    }
    return null;
  }
  private static final String clearBulkLoadTbl = "DELETE FROM DB.DBA.load_list";

  private static void clearBulkLoadHistory(Connection conn) throws SQLException {
      PreparedStatement clearBulkLoadTblStmt;
      clearBulkLoadTblStmt = conn.prepareStatement(clearBulkLoadTbl);                        
      clearBulkLoadTblStmt.executeUpdate();
  }

}
```
- I have tried to run your code,
```
ttlp(file_to_string('./test.ttl'), 'urn:test', 'urn:test', 0);
```
but I don't know how to pass local TTL file path to source path.is there any place where I have to put my test.ttl file to get access because I am new to this tried to find on google but didn't find the answer.

is there anything else you need.please let me know?.
Thanks for your help and time.Appreciate it.

**Comment by TallTed** [comment]
Is there something preventing you from upgrading from that very old VOS (Virtuoso Open Source) v6, to the [nearly-current v7.2.4.2](http://vos.openlinksw.com/owiki/wiki/VOS/VOSNews) (`stable/7`) or [v7.2.5 or later](https://github.com/openlink/virtuoso-opensource/tree/develop/7) (`develop/7`)?

This upgrade is strongly recommended, as there have been [many dozens if not several hundred fixes and enhancements](https://github.com/openlink/virtuoso-opensource/commits/develop/7) in the intervening 5.5+ years!

As to your latest question, the local TTL file must be within a directory included in the [INI file's `DirsAllowed` (in the `
[Parameters]` section)](http://docs.openlinksw.com/virtuoso/dbadm/#ini_parameters_dirsallowed).  You can add `.` (note that this is relative to the active INI file) to that list, or move your file to a directory already listed.
