### ISSUE TITLE
Memory leak in virtuoso.jdbc4.VirtuosoStatement.close()

### ISSUE THREAD

**Issue by ghost** [openlink/virtuoso-opensource#73]
Because VirtuosoStatement.finalizer() calls this.close() which accquire monitor on connection(which one of few from connection pool) the finalizer queue grows very fast(thousands of objects) even if Statement are closed programmatic by program(or VirtGraph). 
On loaded apps this tend to OOM.

=== STACK TRACE ===
"Finalizer" daemon prio=10 tid=0x00007f04880b2000 nid=0x3b3a waiting for monitor entry [0x00007f04842d0000]
java.lang.Thread.State: BLOCKED (on object monitor)
at virtuoso.jdbc4.VirtuosoPreparedStatement.close(Unknown Source)
(waiting to lock <0x0000000722ac3a58> (a virtuoso.jdbc4.VirtuosoConnection))
at virtuoso.jdbc4.VirtuosoStatement.finalize(Unknown Source)
at java.lang.ref.Finalizer.invokeFinalizeMethod(Native Method)
at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:101)
at java.lang.ref.Finalizer.access$100(Finalizer.java:32)
at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:190)
=== STACK TRACE ===

**Comment by openlink** [comment]
I applied this patch manually to develop/6 and develop/7 branches.
