### ISSUE TITLE
 An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by A7medDaoud** [openlink/virtuoso-opensource#897]
when trying to SaveGraph to virtuoso using **VirtuosoManager** class in C#
I got that exception: **"An unhandled exception of type 'System.Net.Sockets.SocketException' occurred in virtado4.dll"**

**I'm using the following:**
assemblies: **dotNetRDF.Data.Virtuoso**,  **virtado4**
Virtuoso version: Virtuoso Open Source Edition (multi-threaded)
Version 7.0.0.3229-threads as of Aug 27, 2018
compiled for Win64 (x86-64-generic-win-64)

**important note:**
when testing i noticed something important that i don't get any errors for triples (nearly less than 118200 Triples or nearly 16 Mbytes file size) but for any larger file, it gives me the above Exception.

**here is the Exception stack trace:**
  at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
  at OpenLink.Data.Virtuoso.TcpStream.Flush()
  at OpenLink.Data.Virtuoso.TcpStream.Write(Byte[] buffer, Int32 offset, Int32 count)
  at System.IO.Stream.WriteByte(Byte value)
  at OpenLink.Data.Virtuoso.Marshaler.Marshal(Stream stream, Hashtable map, Object value)
  at OpenLink.Data.Virtuoso.TcpSession.Write(Object value)
  at OpenLink.Data.Virtuoso.Future.SendRequest(ISession session, Int32 timeout)
  at OpenLink.Data.Virtuoso.Future.SendRequest(ISession session)
  at OpenLink.Data.Virtuoso.ManagedConnection.EndTransaction(Boolean commit)
  at OpenLink.Data.Virtuoso.VirtuosoConnection.EndTransaction(Boolean commit)
  at OpenLink.Data.Virtuoso.VirtuosoTransaction.End(Boolean commit)
  at OpenLink.Data.Virtuoso.VirtuosoTransaction.Commit()
  at VDS.RDF.Storage.VirtuosoManager.Close(Boolean forceClose, Boolean rollbackTrans)
  at VDS.RDF.Storage.VirtuosoManager.Close(Boolean forceClose)
  at VDS.RDF.Storage.VirtuosoManager.SaveGraph(IGraph g)

**and the log file error in (virtuoso.log):**
Malformed data received from IP [127.0.0.1] : Box length too large. Disconnecting the client

**Comment by HughWilliams** [comment]
Hi Ahmed,

There is a limit of 10Mb per string box in Virtuoso, thus you are seeking to load files large then  should consider using the Virtuoso RDF Bulk Loader which is designed for loading large datasets as detailed at:

   http://vos.openlinksw.com/owiki/wiki/VOS/VirtBulkRDFLoader

Or if you have to continue using the ADO.Net client interface will need to split file to ensure they are not larger then 10MB ...

**Comment by A7medDaoud** [comment]
thank you @HughWilliams
