### ISSUE TITLE
Java finalizer usage can block

### ISSUE THREAD

**Issue by JervenBolleman** [openlink/virtuoso-opensource#965]
From a stack dump in a production setting

From the finalizer thread: Blocked while waiting to lock on a VirtuosoConnection
```
"Finalizer" #3 daemon prio=8 os_prio=0 cpu=5455.76ms elapsed=419295.36s tid=0x00007fd8684d4800 nid=
0xff03c waiting for monitor entry  [0x00007fcee28ec000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at virtuoso.jdbc4.VirtuosoStatement.close_rs(VirtuosoStatement.java:178)
        - waiting to lock <0x00007fcf7e08cd68> (a virtuoso.jdbc4.VirtuosoConnection)
        at virtuoso.jdbc4.VirtuosoStatement.close(VirtuosoStatement.java:211)
        at virtuoso.jdbc4.VirtuosoStatement.finalize(VirtuosoStatement.java:146)
        at java.lang.System$2.invokeFinalize(java.base@11.0.11/System.java:2125)
        at java.lang.ref.Finalizer.runFinalizer(java.base@11.0.11/Finalizer.java:87)
        at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.11/Finalizer.java:171)
```
While that connection is in use by living code:

```
"RDFLoader calling thread 22" #55 prio=5 os_prio=0 cpu=1.12ms elapsed=419163.51s tid=0x00007fd868bf
3800 nid=0xff160 runnable  [0x00007fcd9adec000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(java.base@11.0.11/Native Method)
        at java.net.SocketInputStream.socketRead(java.base@11.0.11/SocketInputStream.java:115)
        at java.net.SocketInputStream.read(java.base@11.0.11/SocketInputStream.java:168)
        at java.net.SocketInputStream.read(java.base@11.0.11/SocketInputStream.java:140)
        at java.io.BufferedInputStream.fill(java.base@11.0.11/BufferedInputStream.java:252)
        at java.io.BufferedInputStream.read(java.base@11.0.11/BufferedInputStream.java:271)
        - locked <0x00007fcf7e08cd28> (a virtuoso.jdbc4.VirtuosoInputStream)
        at virtuoso.jdbc4.VirtuosoInputStream.read(VirtuosoInputStream.java:14)
        at virtuoso.jdbc4.VirtuosoInputStream.read_object(VirtuosoInputStream.java:50)
        at virtuoso.jdbc4.VirtuosoConnection.read_request(VirtuosoConnection.java:484)
        at virtuoso.jdbc4.VirtuosoFuture.nextResult(VirtuosoFuture.java:55)
        at virtuoso.jdbc4.VirtuosoResultSet.process_result(VirtuosoResultSet.java:215)
        at virtuoso.jdbc4.VirtuosoResultSet.getMoreResults(VirtuosoResultSet.java:84)
        - locked <0x00007fcf7e08cd68> (a virtuoso.jdbc4.VirtuosoConnection)
        at virtuoso.jdbc4.VirtuosoPreparedStatement.sendQuery(VirtuosoPreparedStatement.java:87)
        - locked <0x00007fcf7e08cd68> (a virtuoso.jdbc4.VirtuosoConnection)
        at virtuoso.jdbc4.VirtuosoPreparedStatement.executeUpdate(VirtuosoPreparedStatement.java:117)
```

Finalizers should be minimal and their locking should be as constrained as possible.

**Comment by smalinin** [comment]
You must properly close ResultSets and Statements for avoid this problem with finalizers. 
If you don't close ResultSet/Statement in your Java code, we need call **close** in finilalizer for avoid exhaustion free statemets on server side.
p.s.
I need some example, if you don't agree with this.

**Comment by JervenBolleman** [comment]
I agree with the state that close must be called (and gosh am I looking where that statement is coming from). 

However, the finalizer does not guarantee resource exhaustion on the server side. Secondly the way they are calling each other may lead to deadlocks between different parts of the code. Specifically, ordering between of closing sub elements + gc can lead to long lasting locks here. Basically the different finalizers may block on each other and or other code so they must be limited in scope. The pull request does not remove finalizers it just reduces their scope to actually do the required work of cleaning up server resources.

**Comment by smalinin** [comment]
@JervenBolleman 
I prepared fix based on your pull request. 
Not at all updates could be applied. 
It will be in git repo soon.

**Comment by JervenBolleman** [comment]
Sorry about that. I failed to notice that my compile actually failed in the C code, so ended up not testing the java code I thought I was testing.

Would you be open to a pull request reorganizing the java code subdirectories to be more in a more common layout?

**Comment by TallTed** [comment]
@JervenBolleman -- May we consider this issue closed, given the commit above, and your closure of #966?

**Comment by JervenBolleman** [comment]
@TallTed  yes. I still recommend and am willing to help to eradicate all finalizer uses. But the situation has improved a bit.

**Comment by TallTed** [comment]
@JervenBolleman -- Your efforts are appreciated! 

Unfortunately, due to the patterns of our development work, PRs against the VOS repos can rarely be applied directly or completely -- but reproduction steps for any observable issues are always helpful, as are pointers to and suggested fixes for specific bugs in the code, which do help us resolve them in our internal codebase, and then apply those fixes to the VOS tree here.
